services:
  postgres:
    image: postgres:16
    container_name: querysence-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-querysence}
      POSTGRES_USER: ${POSTGRES_USER:-amine}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-amine} -d ${POSTGRES_DB:-querysence}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - internal

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: querysence-keycloak
    restart: unless-stopped
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER:-amine}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak/querysence-realm.json:/opt/keycloak/data/import/querysence-realm.json:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal

  backend:
    build:
      context: ./querysence-back
      dockerfile: Dockerfile
    container_name: querysence-backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/querysence
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      DB_CONNECTION_ENCRYPTION_KEY: ${DB_CONNECTION_ENCRYPTION_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_BASE_URL: ${GROQ_BASE_URL}
      GROQ_MODEL: ${GROQ_MODEL}
    ports:
      - "8082:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - user_databases

volumes:
  pgdata:

networks:
  internal:
    driver: bridge

  user_databases:
    external: true

